apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: dr-static
  namespace: default
spec:
  period: 1m
  concurrentScans: 2
  defaultSchema:
    provider: srl.nokia.sdcio.dev
    version: 24.10.1
  addresses:
  - address: 172.80.80.21
    hostName: spine1
  - address: 172.80.80.22
    hostName: spine2
  - address: 172.80.80.11
    hostName: leaf1
  - address: 172.80.80.12
    hostName: leaf2
  - address: 172.80.80.13
    hostName: leaf3
  targetConnectionProfiles:
  - credentials: srl.nokia.sdcio.dev
    connectionProfile: gnmi-skipverify
    syncProfile: gnmi-get
  targetTemplate:
    labels:
      sdcio.dev/region: us-east
