apiVersion: v1
kind: ConfigMap
metadata:
  name: vidra-config
  labels:
    app: vidra # Important: This label is used to identify the operator's resources.
  namespace: vidra-system
data:
  requeueSyncAfter: "1m" # How often Vidra syncs with Infrahub. (if you do not want to use the default value of 1 minute)
  requeueResourcesAfter: "1m" # How often managed resources are reconciled. (if you do not want to use the default value of 10 minutes)
  queryName: "ArtifactIDs" # Infrahub GraphQL query name for getting Artifact IDs. (if you do not want to use the default value of "ArtifactIDs")
  eventBasedReconcile: "true" # Enable event-based reconciliation. (default is false)
---
apiVersion: v1
kind: Secret
metadata:
  name: infrahub-credentials
  namespace: vidra-system
  labels:
    infrahub-api-url: "192.168.97.1" # Important: This label is used to identify the operator's resources.
data:
  username: YWRtaW4=
  password: aW5mcmFodWI=
---
apiVersion: infrahub.operators.com/v1alpha1
kind: InfrahubSync
metadata:
  name: sync-test-webserver
  labels:
    app.kubernetes.io/name: vidra
    app.kubernetes.io/managed-by: kustomize
spec:
  source:
    infrahubAPIURL: "http://192.168.97.1:8000"
    targetBranch: "main"
    artefactName: "sdc_srlinux_interface_artifact"
